# Generated by Django 6.0.3 on 2026-03-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('size_width', models.IntegerField()),
                ('size_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.FloatField()),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RampType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=100)),
                ('floors', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.elevator')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistans', models.BooleanField()),
                ('ramps', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.ramps')),
            ],
        ),
        migrations.AddField(
            model_name='ramps',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.ramptype'),
        ),
    ]
