# Generated by Django 6.0.6 on 2026-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.RemoveField(
            model_name='ramps',
            name='type',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
