# Generated by Django 6.0.6 on 2026-07-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_house_city_remove_ramps_type_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='house',
            name='ramps',
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Доступность', 'verbose_name_plural': 'Варианты доступности'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AddField(
            model_name='house',
            name='elevator_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина лифта (см)'),
        ),
        migrations.AddField(
            model_name='house',
            name='elevator_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина лифта (см)'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Есть лифт'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='Есть пандус'),
        ),
        migrations.AddField(
            model_name='house',
            name='ramp_degrees',
            field=models.FloatField(blank=True, null=True, verbose_name='Угол наклона пандуса (°)'),
        ),
        migrations.AddField(
            model_name='house',
            name='ramp_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина пандуса (м)'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='assistance',
            field=models.BooleanField(default=False, verbose_name='Требуется помощь'),
        ),
        migrations.AlterField(
            model_name='house',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.availability', verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(max_length=500, verbose_name='Улица'),
        ),
        migrations.DeleteModel(
            name='Elevator',
        ),
        migrations.DeleteModel(
            name='Ramps',
        ),
    ]
