"""
Django settings for map project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y2@_3sn%@%*=5m+x&@94ulp7tk_s-cv1d7dfe@9%w!7ynd!hi*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'map.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'map.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --------------------------------Настройки для библиотеки Django REST Framework для обработки запросов к API---------------------------------
REST_FRAMEWORK = {
    # -----pagination для обработки запросов на получение списка объектов с поддержкой пагинации, что позволяет клиенту получать данные порциями и управлять количеством данных, получаемых за один запрос-----
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination', # добавление
    'PAGE_SIZE': 3, # установка количества объектов, возвращаемых за один запрос при использовании пагинации, что позволяет клиенту получать данные порциями и управлять количеством данных, получаемых за один запрос
    
    # ---------Настройки для обработки запросов и ответов в формате JSON и предоставления удобного интерфейса для тестирования и взаимодействия с API через веб-браузер---------------
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer', # добавление JSONRenderer для обработки запросов и ответов в формате JSON, 
        # что позволяет клиенту получать данные в формате JSON и отправлять данные в формате JSON при взаимодействии с API
        'rest_framework.renderers.BrowsableAPIRenderer', # добавление BrowsableAPIRenderer для предоставления удобного интерфейса для тестирования и взаимодействия с API через веб-браузер,
        # что позволяет разработчикам и пользователям легко просматривать и тестировать API через веб-браузер, providing a convenient interface for sending requests and viewing responses in JSON format
    ],
    
    # ---------Настройки для обработки разрешений доступа к API---------------
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # разрешение доступа к API для всех пользователей, включая неавторизованных, без ограничения доступа к данным, данные передаются в формате JSON
    ],
    
    # ---------Настройки для обработки аутентификации пользователей через API с помощью различных методов аутентификации---------------
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication', # добавление TokenAuthentication для обработки аутентификации пользователей через API с использованием токенов, что позволяет клиенту аутентифицироваться с помощью токена при взаимодействии с API
        'rest_framework.authentication.SessionAuthentication', # добавление SessionAuthentication для обработки аутентификации пользователей через API с использованием сессий, что позволяет клиенту аутентифицироваться с помощью сессии при взаимодействии с API
        'rest_framework.authentication.BasicAuthentication', # добавление BasicAuthentication для обработки аутентификации пользователей через API с использованием базовой аутентификации, что позволяет клиенту аутентифицироваться с помощью имени пользователя и пароля при взаимодействии с API
        'rest_framework_simplejwt.authentication.JWTAuthentication', # добавление JWTAuthentication для обработки аутентификации пользователей через API с использованием JSON Web Tokens, что позволяет клиенту аутентифицироваться с помощью JWT при взаимодействии с API
    ],
}

# -------------------------------Настройки для библиотеки Simple JWT для обработки аутентификации пользователей через API с использованием JSON Web Tokens---------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}